# Generated by Django 3.2 on 2022-01-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='134F22', max_length=6),
        ),
    ]
