# Generated by Django 3.2 on 2022-01-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20220119_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='29DE60', max_length=6),
        ),
    ]
